/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  FlashcardOrderByInput: { // input type
    createdAt?: NexusGenEnums['Sort'] | null; // Sort
    hardness?: NexusGenEnums['Sort'] | null; // Sort
    title?: NexusGenEnums['Sort'] | null; // Sort
  }
  LinkOrderByInput: { // input type
    createdAt?: NexusGenEnums['Sort'] | null; // Sort
    description?: NexusGenEnums['Sort'] | null; // Sort
    url?: NexusGenEnums['Sort'] | null; // Sort
  }
}

export interface NexusGenEnums {
  Sort: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Category: { // root type
    flashCards?: Array<NexusGenRootTypes['FlashCard'] | null> | null; // [FlashCard]
    id: number; // Int!
    name: string; // String!
  }
  Feed: { // root type
    count: number; // Int!
    id?: string | null; // ID
    links: NexusGenRootTypes['Link'][]; // [Link!]!
  }
  FlashCard: { // root type
    answer: string; // String!
    categoryId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    hardness: string; // String!
    id: number; // Int!
    question: string; // String!
    title: string; // String!
  }
  Flip: { // root type
    link: NexusGenRootTypes['Link']; // Link!
    user: NexusGenRootTypes['User']; // User!
  }
  Link: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: number; // Int!
    url: string; // String!
  }
  Mutation: {};
  Query: {};
  Read: { // root type
    flashCard: NexusGenRootTypes['FlashCard']; // FlashCard!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // root type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Category: { // field return type
    flashCards: Array<NexusGenRootTypes['FlashCard'] | null> | null; // [FlashCard]
    id: number; // Int!
    name: string; // String!
  }
  Feed: { // field return type
    count: number; // Int!
    id: string | null; // ID
    links: NexusGenRootTypes['Link'][]; // [Link!]!
  }
  FlashCard: { // field return type
    answer: string; // String!
    category: NexusGenRootTypes['Category'] | null; // Category
    categoryId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    createdBy: NexusGenRootTypes['User'] | null; // User
    hardness: string; // String!
    id: number; // Int!
    question: string; // String!
    readers: NexusGenRootTypes['User'][]; // [User!]!
    title: string; // String!
  }
  Flip: { // field return type
    link: NexusGenRootTypes['Link']; // Link!
    user: NexusGenRootTypes['User']; // User!
  }
  Link: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    flipers: NexusGenRootTypes['User'][]; // [User!]!
    id: number; // Int!
    postedBy: NexusGenRootTypes['User'] | null; // User
    url: string; // String!
  }
  Mutation: { // field return type
    createCategory: NexusGenRootTypes['Category'] | null; // Category
    createFlashCard: NexusGenRootTypes['FlashCard']; // FlashCard!
    flip: NexusGenRootTypes['Flip'] | null; // Flip
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    post: NexusGenRootTypes['Link']; // Link!
    read: NexusGenRootTypes['Read'] | null; // Read
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
  }
  Query: { // field return type
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    feed: NexusGenRootTypes['Feed']; // Feed!
    flashCards: Array<NexusGenRootTypes['FlashCard'] | null> | null; // [FlashCard]
  }
  Read: { // field return type
    flashCard: NexusGenRootTypes['FlashCard']; // FlashCard!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    email: string; // String!
    flips: NexusGenRootTypes['Link'][]; // [Link!]!
    id: number; // Int!
    links: NexusGenRootTypes['Link'][]; // [Link!]!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Category: { // field return type name
    flashCards: 'FlashCard'
    id: 'Int'
    name: 'String'
  }
  Feed: { // field return type name
    count: 'Int'
    id: 'ID'
    links: 'Link'
  }
  FlashCard: { // field return type name
    answer: 'String'
    category: 'Category'
    categoryId: 'Int'
    createdAt: 'DateTime'
    createdBy: 'User'
    hardness: 'String'
    id: 'Int'
    question: 'String'
    readers: 'User'
    title: 'String'
  }
  Flip: { // field return type name
    link: 'Link'
    user: 'User'
  }
  Link: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    flipers: 'User'
    id: 'Int'
    postedBy: 'User'
    url: 'String'
  }
  Mutation: { // field return type name
    createCategory: 'Category'
    createFlashCard: 'FlashCard'
    flip: 'Flip'
    login: 'AuthPayload'
    post: 'Link'
    read: 'Read'
    signup: 'AuthPayload'
  }
  Query: { // field return type name
    categories: 'Category'
    feed: 'Feed'
    flashCards: 'FlashCard'
  }
  Read: { // field return type name
    flashCard: 'FlashCard'
    user: 'User'
  }
  User: { // field return type name
    email: 'String'
    flips: 'Link'
    id: 'Int'
    links: 'Link'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createCategory: { // args
      name: string; // String!
    }
    createFlashCard: { // args
      answer: string; // String!
      categoryId: number; // Int!
      hardness?: string | null; // String
      question: string; // String!
      title: string; // String!
    }
    flip: { // args
      linkId: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    post: { // args
      description: string; // String!
      url: string; // String!
    }
    read: { // args
      flashCardId: number; // Int!
    }
    signup: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
  }
  Query: {
    feed: { // args
      filter?: string | null; // String
      orderBy?: NexusGenInputs['LinkOrderByInput'][] | null; // [LinkOrderByInput!]
      skip?: number | null; // Int
      take?: number | null; // Int
    }
    flashCards: { // args
      orderBy?: NexusGenInputs['FlashcardOrderByInput'][] | null; // [FlashcardOrderByInput!]
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}